// <auto-generated />
namespace WpfApp1.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class updatecolumnFaturadbo : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updatecolumnFaturadbo));
        
        string IMigrationMetadata.Id
        {
            get { return "202302020334330_updatecolumnFaturadbo"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
