// <auto-generated />
namespace WpfApp1.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class update_musteriler_borc : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(update_musteriler_borc));
        
        string IMigrationMetadata.Id
        {
            get { return "202302020522565_update_musteriler_borc"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
